# Generated by Django 4.1.7 on 2023-04-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_profile_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='feedback',
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
