# Generated by Django 4.1.7 on 2023-04-05 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_product_delete_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorie',
        ),
        migrations.AlterModelOptions(
            name='categorie',
            options={},
        ),
        migrations.RenameField(
            model_name='categorie',
            old_name='name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categorie',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created_at',
            new_name='cree_a',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created_by',
            new_name='cree_par',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_sold',
            new_name='is_vznsu',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='prix',
        ),
    ]
