# Generated by Django 4.1.7 on 2023-04-05 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_category_categorie_alter_categorie_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_vznsu',
            new_name='is_vendu',
        ),
    ]
