# Generated by Django 4.1.7 on 2023-04-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='products_images'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='products_images'),
        ),
    ]
