# Generated by Django 4.1.7 on 2023-04-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_favorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categorieProduit',
            field=models.CharField(choices=[('PHONE', 'Phone'), ('ACCESSOIRES', 'Accessoires')], default='PHONE', max_length=255),
        ),
    ]
