# Generated by Django 4.1.7 on 2023-04-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='prix_total',
            field=models.FloatField(default=0.0),
        ),
    ]
