# Generated by Django 4.1.7 on 2023-04-23 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentprocdut',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.profile'),
        ),
    ]
