# Generated by Django 4.1.7 on 2023-04-23 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0026_commentprocdut_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_quantite', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_1', models.CharField(max_length=20)),
                ('phone_2', models.CharField(blank=True, max_length=20, null=True)),
                ('code', models.CharField(max_length=20)),
                ('commune', models.CharField(max_length=200)),
                ('wilaya', models.CharField(max_length=200)),
                ('command_code', models.CharField(blank=True, max_length=20, null=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
