# Generated by Django 4.1.7 on 2023-04-24 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_remove_product_vendu_product_est_vendu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='est_vendu',
            new_name='vendu',
        ),
    ]
