# Generated by Django 4.1.7 on 2023-04-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_rename_est_vendu_product_vendu'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
