# Generated by Django 4.1.7 on 2023-04-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_remove_feedback_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categorieProduit',
            field=models.CharField(choices=[('TELEPHONES', 'Telephones'), ('ACCESSOIRES', 'Accessoires')], default='PHONE', max_length=255),
        ),
    ]
