# Generated by Django 4.1.7 on 2023-04-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_panier'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeform',
            name='command',
            field=models.TextField(blank=True, null=True),
        ),
    ]
