# Generated by Django 4.1.7 on 2023-04-28 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_commandeform_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.profile'),
        ),
    ]
