# Generated by Django 4.1.7 on 2023-04-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentprocdut',
            name='profile',
        ),
        migrations.AddField(
            model_name='commentprocdut',
            name='profile',
            field=models.ManyToManyField(to='myapp.profile'),
        ),
    ]
