# Generated by Django 4.1.7 on 2023-04-29 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_remove_commentprocdut_profile_commentprocdut_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentprocdut',
            name='profile',
        ),
        migrations.AddField(
            model_name='commentprocdut',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.profile'),
        ),
    ]
