# Generated by Django 4.1.7 on 2023-06-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_user_alter_feedback_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeform',
            name='adresse',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
