# Generated by Django 4.1.7 on 2023-06-13 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_commandeform_adresse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandeform',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='commandeform',
            name='product_quantite',
        ),
    ]
