# Generated by Django 4.1.7 on 2023-06-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_remove_commandeform_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeform',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('accepted', 'Accepted'), ('refused', 'Refused')], default='waiting', max_length=20),
        ),
    ]
