# Generated by Django 4.1.7 on 2023-06-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_commandeform_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandeform',
            name='status',
        ),
        migrations.AddField(
            model_name='commande',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('accepted', 'Accepted'), ('refused', 'Refused')], default='waiting', max_length=20),
        ),
    ]
